apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: operator-oadp-group
  namespace: oadp-operator
spec:
  channel: stable
  name: redhat-oadp-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace