global_config:
  environment_name: demo
  cloud_platform: existing-ocp
vault:
  vault_type: file-vault
  vault_authentication_type: none
openshift:
- name: cpd-demo
  ocp_version: '4.10'
  cluster_name: cpd-demo
  domain_name: example.com
  openshift_storage:
  - storage_name: nfs-storage
    storage_type: nfs
