apiVersion: v1
kind: Pod
metadata:
  name: olm-utils
spec:
  containers:
    - name: olm-utils
      image: icr.io/cpopen/olm-utils:pre-release
      imagePullPolicy: Always
      ports:
        - containerPort: 3100
      securityContext:
        privileged: true
  serviceAccount: olm-utils-sa
