from apis.endpoints.assets import AssetsAPI
from apis.endpoints.catalogs import CatalogsAPI
from apis.endpoints.categories import CategoriesAPI
from apis.endpoints.connections import ConnectionsAPI
from apis.endpoints.datarequests import DataRequestAPI
from apis.endpoints.glossaryTerms import TermsAPI
from apis.endpoints.governanceArtifactTypes import GovArtifactAPI
from apis.endpoints.jobs import JobsAPI
from apis.endpoints.projects import ProjectsAPI
from apis.endpoints.rules import RulesAPI
from apis.endpoints.referenceData import RefDataAPI
from apis.endpoints.users import UsersAPI
from apis.endpoints.workflows import WorkflowsAPI
