apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloud-pak-deployer
  name: cloud-pak-deployer
  namespace: cloud-pak-deployer
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: cloud-pak-deployer
  template:
    metadata:
      labels:
        deployment: cloud-pak-deployer
    spec:
      containers:
      - image: quay.io/fketelaars/cloud-pak-deployer:latest
        imagePullPolicy: Always
        name: cloud-pak-deployer
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: CONFIG_DIR
          value: /Data/cpd-config
        - name: STATUS_DIR
          value: /Data/cpd-status
        volumeMounts:
        - mountPath: /Data
          name: cloud-pak-deployer-volume-1
        command: ["/bin/sh","-xc"]
        args: 
          - sleep infinity
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      serviceAccountName: cloud-pak-deployer-sa
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: cloud-pak-deployer-volume-1