apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: cloud-pak-deployer
  name: cloud-pak-deployer
  namespace: cloud-pak-deployer
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  template:
    metadata:
      name: cloud-pak-deployer
      labels:
        app: cloud-pak-deployer
    spec:
      initContainers:
      - name: wait-config
        image: quay.io/fketelaars/cloud-pak-deployer:latest
        command: ['sh', '-c', 'until [ -f /Data/cpd-config/config-ready ]; do ls -al /Data/cpd-config; echo Waiting for /Data/cpd-config/config-ready file; sleep 1; done;echo "Configuration is ready, starting deployer"']
        env:
        - name: CONFIG_DIR
          value: /Data/cpd-config
        - name: STATUS_DIR
          value: /Data/cpd-status
        volumeMounts:
        - mountPath: /Data
          name: cloud-pak-deployer-volume
      containers:
      - image: quay.io/fketelaars/cloud-pak-deployer:latest
        imagePullPolicy: Always
        name: cloud-pak-deployer
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: CONFIG_DIR
          value: /Data/cpd-config
        - name: STATUS_DIR
          value: /Data/cpd-status
        volumeMounts:
        - mountPath: /Data
          name: cloud-pak-deployer-volume
        command: ["/bin/sh","-xc"]
        args: 
          - /cloud-pak-deployer/cp-deploy.sh env apply -v
      restartPolicy: Never
      securityContext:
        runAsUser: 0
      serviceAccountName: cloud-pak-deployer-sa
      volumes:
      - emptyDir: {}
        name: cloud-pak-deployer-volume