curl -k -X POST https://zen-gov-cpd-zen-gov.apps.ocp45.tec.uk.ibm.com/icp4d-api/v1/authorize -H 'cache-control: no-cache' -H 'content-type: application/json' -d '{"username":"admin","password":"password"}'